"""
PDF report generator (ReportLab, fully offline).

Turns an audit result into a clean per-device compliance report an admin can file or
hand to an auditor: score, failures first (severity-ranked), evidence, and the exact
fix commands.
"""
import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Preformatted,
)

_TEAL = colors.HexColor("#0b6b74")
_RED = colors.HexColor("#c0392b")
_GREEN = colors.HexColor("#1e8449")
_GREY = colors.HexColor("#7f8c8d")
_SEV = {"high": _RED, "medium": colors.HexColor("#b9770e"), "low": _GREY}
_RANK = {"high": 0, "medium": 1, "low": 2}


def build_pdf(result):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=16 * mm, bottomMargin=14 * mm,
                            leftMargin=16 * mm, rightMargin=16 * mm)
    ss = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=ss["Title"], textColor=_TEAL, fontSize=20, spaceAfter=2)
    sub = ParagraphStyle("sub", parent=ss["Normal"], textColor=_GREY, fontSize=9)
    h2 = ParagraphStyle("h2", parent=ss["Heading2"], textColor=_TEAL, fontSize=12, spaceBefore=10)
    body = ParagraphStyle("body", parent=ss["Normal"], fontSize=9, leading=12)
    mono = ParagraphStyle("mono", parent=ss["Code"], fontSize=8, leading=10,
                          textColor=colors.HexColor("#22313f"))

    dev = result["device"]
    rep = result["report"]
    story = []

    story.append(Paragraph("Network Security Compliance Report", h1))
    host = dev.get("hostname") or "(unnamed device)"
    story.append(Paragraph(
        f"{host} &nbsp;·&nbsp; vendor: <b>{dev.get('vendor')}</b> "
        f"({dev.get('vendor_status')}) &nbsp;·&nbsp; {datetime.now():%Y-%m-%d %H:%M}", sub))
    story.append(Paragraph(f"Rule pack: {rep.get('pack')} &nbsp;·&nbsp; generated offline", sub))
    story.append(Spacer(1, 8))

    fbs = rep["fails_by_severity"]
    summary = [
        ["Compliance score", "Passed", "Failed", "Not assessed", "Failures (H / M / L)"],
        [f"{rep['score']}%", str(rep["passed"]), str(rep["failed"]), str(rep["na"]),
         f"{fbs['high']} / {fbs['medium']} / {fbs['low']}"],
    ]
    st = Table(summary, colWidths=[34 * mm, 22 * mm, 22 * mm, 28 * mm, 40 * mm])
    st.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _TEAL),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("FONTNAME", (0, 1), (0, 1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 1), (0, 1), _RED if rep["score"] < 70 else _GREEN),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d5dbdb")),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(st)

    # Failures first, severity-ranked, then everything else.
    checks = sorted(result["report"]["checks"],
                    key=lambda c: (c["status"] != "fail", _RANK.get(c["severity"], 3)))

    story.append(Paragraph("Findings", h2))
    for c in checks:
        color = {"pass": _GREEN, "fail": _RED, "na": _GREY}[c["status"]]
        mark = {"pass": "PASS", "fail": "FAIL", "na": "N/A"}[c["status"]]
        head = (f'<font color="{color.hexval()}"><b>{mark}</b></font> '
                f'<b>{c["title"]}</b> '
                f'<font color="{_SEV[c["severity"]].hexval()}">[{c["severity"].upper()}]</font>')
        story.append(Paragraph(head, body))
        story.append(Paragraph(f'{c["detail"]} <font color="#7f8c8d">— {c["reference"]}</font>', body))
        if c["status"] == "fail" and c["fix"]:
            story.append(Paragraph("Fix:", body))
            story.append(Preformatted(c["fix"], mono))
        story.append(Spacer(1, 5))

    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Generated by the Multi-Vendor Network Security Compliance Auditor · runs locally, "
        "no configuration data leaves the device.", sub))

    doc.build(story)
    buf.seek(0)
    return buf.read()
